---
abstract: 'apparently run a function in a higher stack frame'
author:
  - 'David A. Golden <dagolden@cpan.org>'
build_requires:
  Carp: 0
  Test::More: 0.47
configure_requires:
  Module::Build: 0.35
generated_by: 'Module::Build version 0.3508'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Uplevel
no_index:
  directory:
    - examples
    - inc
  package:
    - DB
provides:
  DB:
    file: lib/Sub/Uplevel.pm
  Sub::Uplevel:
    file: lib/Sub/Uplevel.pm
    version: 0.22
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dagolden/sub-uplevel
version: 0.22
