---
name: Sub-Uplevel
version: 0.2001
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: apparently run a function in a higher stack frame
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  perl: 5.006
build_requires:
  Carp: 0
  Test::More: 0.47
provides:
  DB:
    file: lib/Sub/Uplevel.pm
  Sub::Uplevel:
    file: lib/Sub/Uplevel.pm
    version: 0.2001
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
  package:
    - DB
